### ISSUE TITLE
Solo Mode needs adjustment.

### ISSUE THREAD

**Issue by sum1els-com** [jacobsalmela/ascii-planets#25]
##### Version of rulebook and Planet Sheet

ascii_planets_v1.1.0

##### What is the highest score you have seen in a game? How was this accomplished?

My single-player game stalled out after 15 turns with score 422.  I ran out of astronauts, so I couldn't make any more fortifications, and I'd already filled up everything except Military.  I couldn't make any more squadrons for want of pilots, unless buying Military with Currency doesn't require an Astronaut, in which case I could have bought 4 more squadrons and gotten a couple of more points for gaining the last mastery.  I could probably have engineered a higher score if I had built slightly differently I might have been able to build another Lab or Starship rather than an Academy which scores the same (2) as the Astronaut you need to spend to build it.

20 is way too many turns for the single-player game, 10 would be more interesting.

I ended up with 5 Starships, 5 Factories, 4 Labs, 3 Academies, 1 Battleship, and 1 Space Station, which all easily fit on the map without touching or building in mountains.  The fortification placement rules could use an overhaul, to at least make someone consider having to pay to build on a nebula or mountain.

Buying Astronauts with one Currency may be too cheap; I started by building only Factories, and then using cash to buy Astronauts rather than building Academies until late in the game... Currency is much more useful, and spending a single die on 4 Factories results in 4 S, and I can turn any number of S into /, so in the early game it's much more important to ramp up to get all of the dice as quickly as possible.

##### Does the Planet Sheet print correctly (in b&w/color)? Are there any issues when printing it?

It printed OK in greyscale, but the map is a bit difficult to read, as the white characters really blend in, especially the pirates, which I had to look up the PDF.  All of the characters should be black for contrast.

**Comment by jacobsalmela** [comment]
Thank you again.  I'm excited to enhance it further.

**Comment by jacobsalmela** [comment]
I believe most, if not all of this was addressed in https://github.com/jacobsalmela/ascii-planets/releases/tag/v1.2.0 and subsequent releases
